# Netlify config for the Durmah client (Vite/React in /Client)

[build]
  base = "Client"                 # build from the Client folder
  publish = "dist"                # Vite output
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "22"

# Single-page app redirect (so deep links resolve to index.html)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
